                 
variable --->>  |__| --->> objective

## Gene representation and fitness function

In [8]:
import numpy as np

In [2]:
### population ###

# population = [chromosome1, chromosome2, chromosome3,........] 

# pupulation.chromosome.gene

m = 10 #number of chromosomes (candidate solution)
n=2 #number of genes(decision variables / parameters)


### chromosome ###
chromosemes = [{'gene':[],'fitness'=None]}]

### gene ###

In [127]:
import numpy as np
class chromosome:
    def __init__(self, genes=None):
        self.genes = genes if genes else self.generate_genes()
        self.fitness = fitness_function(self.genes)

    def generate_genes(self, length=10):
        return [np.random.choice([0, 1]) for _ in range(length)]
        

class Population:
    def __init__(self, size=10, chromosome_length=10):
        
        self.chromosomes = [chromosome() for _ in range(size)]
        self.size = len(self.chromosomes)
        # self.chromosome_fitness


In [94]:
a=Population()

In [95]:
for chromosome in a.chromosomes:
    print(chromosome.genes,chromosome.fitness)

[1, 0, 1, 1, 1, 0, 1, 1, 1, 0] 7
[1, 0, 1, 1, 0, 1, 1, 0, 0, 1] 6
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1] 4
[1, 1, 1, 0, 0, 0, 0, 1, 1, 1] 6
[0, 0, 1, 0, 0, 1, 1, 1, 1, 0] 5
[1, 1, 0, 1, 0, 1, 0, 0, 1, 1] 6
[0, 0, 1, 0, 1, 1, 0, 0, 0, 1] 4
[0, 1, 0, 1, 1, 1, 1, 0, 1, 1] 7
[1, 1, 0, 0, 1, 1, 0, 1, 0, 1] 6
[1, 1, 1, 1, 0, 0, 0, 1, 1, 0] 6


In [10]:
d= [ch.fitness for ch in a.chromosomes]
d

[6, 3, 6, 6, 4]

In [26]:
a.chromosomes[0].genes

[1, 1, 0, 0, 0, 0, 0, 0, 0, 1]

In [24]:
a.chromosomes[0].fitness

3

In [6]:
def fitness_function(x): # objective function

    # number_of_blades = x[0]
    # length_of_blades = x[1]

    fitness_value = np.sum(x)
    return fitness_value
    
    

In [ ]:
import random

class Chromosome:
    def __init__(self, genes=None):
        self.genes = genes if genes else self.generate_genes()
        self.fitness = None

    def generate_genes(self, length=10):
        return [random.choice([0, 1]) for _ in range(length)]

    def crossover(self, partner):
        crossover_point = random.randint(0, len(self.genes) - 1)
        child_genes = self.genes[:crossover_point] + partner.genes[crossover_point:]
        return Chromosome(child_genes)

    def mutate(self, mutation_rate=0.01):
        for i in range(len(self.genes)):
            if random.random() < mutation_rate:
                self.genes[i] = 1 if self.genes[i] == 0 else 0


class Population:
    def __init__(self, size=10, chromosome_length=10):
        self.size = size
        self.chromosomes = [Chromosome() for _ in range(size)]
        self.generation = 1

    def evaluate_fitness(self, fitness_function):
        for chromosome in self.chromosomes:
            chromosome.fitness = fitness_function(chromosome)

    def select_parents(self):
        # Select parents based on their fitness (roulette wheel selection)
        total_fitness = sum(chromosome.fitness for chromosome in self.chromosomes)
        probabilities = [chromosome.fitness / total_fitness for chromosome in self.chromosomes]
        parents = random.choices(self.chromosomes, probabilities, k=2)
        return parents

    def evolve(self, mutation_rate=0.01):
        new_population = Population(size=self.size)

        # Keep the best chromosome from the current population
        self.chromosomes.sort(key=lambda x: x.fitness, reverse=True)
        new_population.chromosomes[0] = self.chromosomes[0]

        for i in range(1, self.size):
            parent1, parent2 = self.select_parents()
            child = parent1.crossover(parent2)
            child.mutate(mutation_rate)
            new_population.chromosomes[i] = child

        new_population.generation = self.generation + 1
        return new_population


In [39]:
## selection coding an example
## roulet wheel

fitness_value = np.array([10,100,5.5,34,1000,1,200,100,150,90])

#step1 : to normalize fitness values
normalized_fitness_value = fitness_value/np.sum(fitness_value)
print(np.round(normalized_fitness_value,2))

sorted_normalized_fitness_value = -np.sort(-normalized_fitness_value)
print(np.round(sorted_normalized_fitness_value,2))

cumsum = np.zeros(len(fitness_value))

for i in range(len(fitness_value)):
    for j in range(i,len(fitness_value)):
        cumsum[i]+=sorted_normalized_fitness_value[j]

print(np.round(cumsum,3))

R = np.random.rand()
print(R)
for k in range(1,len(cumsum)):
    if R > cumsum[k]:
        parent1 = k-1
        break
R = np.random.rand()
print(R)
idx = None
for k in range(1,len(cumsum)):
    if R > cumsum[k]:
        parent2 = k-1
        break

print(parent1,parent2)

[0.01 0.06 0.   0.02 0.59 0.   0.12 0.06 0.09 0.05]
[0.59 0.12 0.09 0.06 0.06 0.05 0.02 0.01 0.   0.  ]
[1.    0.408 0.29  0.201 0.142 0.083 0.03  0.01  0.004 0.001]
0.31745879976797553
0.6533322803873733
1 0


In [50]:
cumsum

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.round(normalized_fitness_value,2)

array([0.01, 0.06, 0.  , 0.02, 0.59, 0.  , 0.12, 0.06, 0.09, 0.05])

#### selection : coding a roulett wheel function

In [96]:
def selection(population):
    fitness = np.array([ch.fitness for ch in population.chromosomes])
    print(fitness)
    min_fitness = min(fitness)
    if min_fitness<0:
        fitness = fitness+abs(min_fitness)+1
    normalized_fitness = fitness/sum(fitness)
    print(np.round(normalized_fitness,3))
    index_sorted_normalized_fitness = np.argsort(-normalized_fitness)
    print(index_sorted_normalized_fitness)
    sorted_normalized_fitness = -np.sort(-normalized_fitness)
    print(np.round(sorted_normalized_fitness,3))
    size = len(sorted_normalized_fitness)

    cumsum = np.zeros(size)
    for i in range(size):
        cumsum[i]=sum(sorted_normalized_fitness[i:])

    print(cumsum)

    R = np.random.rand()
    print(R)
    for k in range(1,len(cumsum)):
        if R > cumsum[k]:
            print("inside if")
            parent1 = population.chromosomes[index_sorted_normalized_fitness[k-1]]
            break
            
    parent2 = parent1
    while parent2==parent1:
        R = np.random.rand()
        print(R)
        for k in range(1,len(cumsum)):
            if R > cumsum[k]:
                parent2 = population.chromosomes[index_sorted_normalized_fitness[k-1]]
                break

    print(parent1.genes)
    print(parent2.genes)
    return [parent1,parent2]
                

selection(a)

[7 6 4 6 5 6 4 7 6 6]
[0.123 0.105 0.07  0.105 0.088 0.105 0.07  0.123 0.105 0.105]
[0 7 1 3 5 8 9 4 2 6]
[0.123 0.123 0.105 0.105 0.105 0.105 0.105 0.088 0.07  0.07 ]
[1.         0.87719298 0.75438596 0.64912281 0.54385965 0.43859649
 0.33333333 0.22807018 0.14035088 0.07017544]
0.9894761789199622
inside if
0.7619508875086297
[1, 0, 1, 1, 1, 0, 1, 1, 1, 0]
[0, 1, 0, 1, 1, 1, 1, 0, 1, 1]


In [41]:
for chromosome in a.chromosomes:
    print(chromosome.genes,chromosome.fitness)

[1, 1, 0, 1, 1, 1, 1, 1, 0, 1] 8
[0, 0, 0, 0, 1, 1, 1, 1, 1, 0] 5
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0] 3
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1] 2
[0, 0, 1, 1, 1, 1, 0, 0, 0, 0] 4


#### crossover

In [97]:
parent1 , parent2 = selection(a)
print(parent1)
print(parent2)


[7 6 4 6 5 6 4 7 6 6]
[0.123 0.105 0.07  0.105 0.088 0.105 0.07  0.123 0.105 0.105]
[0 7 1 3 5 8 9 4 2 6]
[0.123 0.123 0.105 0.105 0.105 0.105 0.105 0.088 0.07  0.07 ]
[1.         0.87719298 0.75438596 0.64912281 0.54385965 0.43859649
 0.33333333 0.22807018 0.14035088 0.07017544]
0.7269641138317389
inside if
0.7277463259905649
0.566528284717964
[1, 0, 1, 1, 0, 1, 1, 0, 0, 1]
[1, 1, 1, 0, 0, 0, 0, 1, 1, 1]


In [52]:
# single-point crossover using loops
gene_no = len(parent1.genes)
ub = gene_no
lb = 1
cross_p = np.random.randint(lb,ub) #crossover point
print(cross_p)
child1 = [0]*gene_no
for i in range(gene_no):
    if i<cross_p:
        child1[i]=parent1.genes[i]
    else:
        child1[i]=parent2.genes[i]
print(child1)
child1 = chromosome(child1)


child2 = [0]*gene_no
for i in range(gene_no):
    if i<cross_p:
        child2[i]=parent2.genes[i]
    else:
        child2[i]=parent1.genes[i]
child2 = chromosome(child2)

# child1 = chromosome(parent1.genes[:cross_p]+parent2.genes[cross_p:])
# child2 = chromosome(parent2.genes[:cross_p]+parent1.genes[cross_p:])

print('parent1',parent1.genes,parent1.fitness)
print('parent2',parent2.genes,parent2.fitness)
print('child1',child1.genes,child1.fitness)
print('child2',child2.genes,child2.fitness)




4
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0]
parent1 [0, 1, 0, 0, 1, 1, 0, 0, 0, 0] 3
parent2 [0, 0, 1, 1, 1, 1, 0, 0, 0, 0] 4
child1 [0, 1, 0, 0, 1, 1, 0, 0, 0, 0] 3
child2 [0, 0, 1, 1, 1, 1, 0, 0, 0, 0] 4


In [104]:
# double-point crossover using loops

print(parent1)
print(parent2)
gene_no = len(parent1.genes)
ub = gene_no
lb = 1
cross_p1 = np.random.randint(lb,ub) #crossover point
cross_p2=cross_p1
while cross_p2==cross_p1:
    cross_p2 = np.random.randint(lb,ub)
if cross_p1>cross_p2:
    cross_p1,cross_p2 = cross_p2,cross_p1
print(cross_p1,cross_p2)

part1 = parent1.genes[:cross_p1]
part2 = parent2.genes[cross_p1:cross_p2]
part3 = parent1.genes[cross_p2:]
child1 = part1+part2+part3

print(child1)
child1 = chromosome(child1)
print(child1.genes,child1.fitness)


part1 = parent2.genes[:cross_p1]
part2 = parent1.genes[cross_p1:cross_p2]
part3 = parent2.genes[cross_p2:]
child2 = part1+part2+part3

print(child2)
child2 = chromosome(child2)
print(child2.genes,child2.fitness)

2 4
[1, 0, 1, 0, 0, 1, 1, 0, 0, 1]
[1, 0, 1, 0, 0, 1, 1, 0, 0, 1] 5
[1, 1, 1, 1, 0, 0, 0, 1, 1, 1]
[1, 1, 1, 1, 0, 0, 0, 1, 1, 1] 7


In [105]:
def crossover(parent1,parent2, Pc,crossoverName):
    if crossoverName=='double':
        gene_no = len(parent1.genes)
        ub = gene_no
        lb = 1
        cross_p1 = np.random.randint(lb,ub) #crossover point
        cross_p2=cross_p1
        while cross_p2==cross_p1:
            cross_p2 = np.random.randint(lb,ub)
        if cross_p1>cross_p2:
            cross_p1,cross_p2 = cross_p2,cross_p1
            
        part1 = parent1.genes[:cross_p1]
        part2 = parent2.genes[cross_p1:cross_p2]
        part3 = parent1.genes[cross_p2:]
        child1 = part1+part2+part3
        
        child1 = chromosome(child1)
        
        
        part1 = parent2.genes[:cross_p1]
        part2 = parent1.genes[cross_p1:cross_p2]
        part3 = parent2.genes[cross_p2:]
        child2 = part1+part2+part3
        child2 = chromosome(child2)

        # return [child1,child2]
        
    elif crossoverName=='double':
        pass

    r1 = np.random.rand()
    if r1<Pc:
        child1 = child1
    else:
        child1 = parent1

    r2 = np.random.rand()
    if r2<Pc:
        child2 = child2
    else:
        child2=parent2

    return [child1,child2]
        
    
    

In [106]:
Pc = 0.5
crossoverName = "double"
child1, child2 = crossover(parent1,parent2, Pc, crossoverName)
print(child1.genes,child1.fitness)
print(child2.genes,child2.fitness)

[1, 0, 1, 1, 0, 1, 0, 1, 1, 1] 7
[1, 1, 1, 0, 0, 0, 0, 1, 1, 1] 6


In [169]:
def mutation(child,Pm):
    gene_no = len(child.genes)
    for k in range(len(child.genes)):
        r = np.random.rand()
        # print(k,r,child.genes)
        if r<Pm:
            child.genes[k]=np.logical_not(child.genes[k]).astype(int)
            # child.genes[k] = abs(child.genes[k]-1)
            
    return child
            

In [118]:
np.logical_not(1).astype(int)

0

In [142]:
np.random.rand()

0.8195040559368935

In [170]:
# a = population
new_population = Population() # work on this
for i in range(0,5,2):
    print('------------------------',i,i+1)
    #selection)
    parent1,parent2 = selection(a)

    #crossover
    Pc = 0.5
    crossoverName='double'
    child1,child2 = crossover(parent1,parent2, Pc, crossoverName)

    #mutation
    Pm = 0.5;
    child1 = mutation(child1,Pm)
    child2 = mutation(child2,Pm)

    #elitism
    Er = 0.1
    elites_no = np.round(10*Er )
    
    new_population.chromosomes[i] = child1
    new_population.chromosomes[i+1] = child2

    


    
print("----------------------------------------")
for ele in new_population.chromosomes:
    print(ele.genes,ele.fitness)
    
    

------------------------ 0 1
[7 6 4 6 5 6 4 7 6 6]
[0.123 0.105 0.07  0.105 0.088 0.105 0.07  0.123 0.105 0.105]
[0 7 1 3 5 8 9 4 2 6]
[0.123 0.123 0.105 0.105 0.105 0.105 0.105 0.088 0.07  0.07 ]
[1.         0.87719298 0.75438596 0.64912281 0.54385965 0.43859649
 0.33333333 0.22807018 0.14035088 0.07017544]
0.6039326317325566
inside if
0.6583642021567229
[1, 1, 1, 0, 0, 0, 0, 1, 1, 1]
[0, 1, 0, 1, 1, 0, 0, 1, 1, 0]
------------------------ 2 3
[7 6 4 6 5 6 4 7 6 6]
[0.123 0.105 0.07  0.105 0.088 0.105 0.07  0.123 0.105 0.105]
[0 7 1 3 5 8 9 4 2 6]
[0.123 0.123 0.105 0.105 0.105 0.105 0.105 0.088 0.07  0.07 ]
[1.         0.87719298 0.75438596 0.64912281 0.54385965 0.43859649
 0.33333333 0.22807018 0.14035088 0.07017544]
0.9245028657416484
inside if
0.43603227583810755
[1, 0, 1, 1, 1, 0, 1, 1, 1, 0]
[0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
------------------------ 4 5
[7 6 4 6 5 6 4 7 6 6]
[0.123 0.105 0.07  0.105 0.088 0.105 0.07  0.123 0.105 0.105]
[0 7 1 3 5 8 9 4 2 6]
[0.123 0.123 0.105 0.105

In [110]:
#original population
for chromosome in a.chromosomes:
    print(chromosome.genes,chromosome.fitness)

[1, 0, 1, 1, 1, 0, 1, 1, 1, 0] 7
[1, 0, 1, 1, 0, 1, 1, 0, 0, 1] 6
[1, 0, 0, 0, 1, 0, 1, 0, 0, 1] 4
[1, 1, 1, 0, 0, 0, 0, 1, 1, 1] 6
[0, 0, 1, 0, 0, 1, 1, 1, 1, 0] 5
[1, 1, 0, 1, 0, 1, 0, 0, 1, 1] 6
[0, 0, 1, 0, 1, 1, 0, 0, 0, 1] 4
[0, 1, 0, 1, 1, 1, 1, 0, 1, 1] 7
[1, 1, 0, 0, 1, 1, 0, 1, 0, 1] 6
[1, 1, 1, 1, 0, 0, 0, 1, 1, 0] 6


In [172]:
[ch.fitness for ch in a.chromosomes]


[7, 6, 4, 6, 5, 6, 4, 7, 6, 6]

In [160]:
Pm = 1
ac =chromosome([1,1,1,1,1,1,1,1,1,1])

In [161]:
mutation(ac,1)

In [162]:
ac.genes

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [151]:
xx = mutation(ac.gene,1)
xx

In [156]:
ac.genes

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [158]:
for i in range(len(ac.genes)):
    ac.genes[i]=(abs(ac.genes[i]-1))
ac.genes

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [173]:
a

In [176]:
for ch in a.chromosomes:
    print(ch.genes,ch.fitness)

[1, 0, 1, 1, 1, 0, 1, 1, 1, 0] 7
[1, 1, 0, 1, 1, 0, 0, 1, 0, 0] 6
[1, 1, 1, 0, 1, 1, 0, 0, 1, 0] 4
[1, 0, 0, 0, 0, 1, 0, 1, 0, 0] 6
[0, 1, 0, 1, 0, 1, 0, 0, 0, 0] 5
[1, 1, 0, 1, 0, 1, 0, 0, 1, 1] 6
[0, 0, 1, 0, 1, 1, 0, 0, 0, 1] 4
[0, 1, 0, 1, 1, 1, 1, 0, 1, 1] 7
[0, 0, 1, 0, 0, 1, 1, 0, 0, 0] 6
[1, 1, 1, 1, 0, 0, 0, 1, 1, 0] 6


In [177]:
new_population = Population()

for ch in new_population.chromosomes:
    print(ch.genes,ch.fitness)

[1, 1, 0, 0, 0, 0, 0, 1, 1, 1] 5
[0, 0, 1, 1, 0, 0, 0, 0, 0, 1] 3
[0, 1, 0, 0, 1, 1, 0, 1, 0, 0] 4
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1] 8
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1] 5
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0] 2
[1, 1, 0, 0, 0, 1, 1, 1, 0, 0] 5
[1, 1, 1, 0, 0, 1, 1, 1, 0, 0] 6
[0, 0, 1, 1, 1, 1, 0, 1, 1, 1] 7
[0, 1, 0, 1, 1, 0, 0, 1, 0, 0] 4


In [ ]:
new_population = elitism(a,new_population,Er=0.2)

In [ ]:
def elitism(population,new_population,Er=0.2):
    m = len(new_population)
    fitness = np.array([ch.fitness for ch in population.chromosomes])
    index_sorted = np.argsort(-normalized_fitness)
    

In [179]:
fitness = np.array([ch.fitness for ch in a.chromosomes])
fitness

array([7, 6, 4, 6, 5, 6, 4, 7, 6, 6])

In [181]:
index_sorted = np.argsort(-fitness)
index_sorted

array([0, 7, 1, 3, 5, 8, 9, 4, 2, 6], dtype=int64)