In [31]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
graph_data = [
        [0, 2451, 713, 1018, 1631, 1374, 2408, 213, 2571, 875, 1420, 2145, 1972],
        [2451, 0, 1745, 1524, 831, 1240, 959, 2596, 403, 1589, 1374, 357, 579],
        [713, 1745, 0, 355, 920, 803, 1737, 851, 1858, 262, 940, 1453, 1260],
        [1018, 1524, 355, 0, 700, 862, 1395, 1123, 1584, 466, 1056, 1280, 987],
        [1631, 831, 920, 700, 0, 663, 1021, 1769, 949, 796, 879, 586, 371],
        [1374, 1240, 803, 862, 663, 0, 1681, 1551, 1765, 547, 225, 887, 999],
        [2408, 959, 1737, 1395, 1021, 1681, 0, 2493, 678, 1724, 1891, 1114, 701],
        [213, 2596, 851, 1123, 1769, 1551, 2493, 0, 2699, 1038, 1605, 2300, 2099],
        [2571, 403, 1858, 1584, 949, 1765, 678, 2699, 0, 1744, 1645, 653, 600],
        [875, 1589, 262, 466, 796, 547, 1724, 1038, 1744, 0, 679, 1272, 1162],
        [1420, 1374, 940, 1056, 879, 225, 1891, 1605, 1645, 679, 0, 1017, 1200],
        [2145, 357, 1453, 1280, 586, 887, 1114, 2300, 653, 1272, 1017, 0, 504],
        [1972, 579, 1260, 987, 371, 999, 701, 2099, 600, 1162, 1200, 504, 0],
    ]

In [33]:
def objective_function(tour, graph):
    fitness = 0

    for i in range(len(tour) - 1):
        current_node = tour[i]
        next_node = tour[i + 1]

        fitness += graph[current_node][next_node]

    fitness = -fitness  # SA is for maximization, so multiply by -1 to change the minimization problem to a maximization problem
    return fitness

In [34]:
def create_neighbour(A):
    index = np.random.choice(len(A), 2, replace=False)

    i, j = index[0], index[1]
    
    B = np.copy(A)
    B[i] = A[j]
    B[j] = A[i]
    
    return B

In [35]:
# Function 6: Simulated Annealing
def simulated_annealing(graph_data):
    # graph_data = create_graph(graph_no)
    n_var = len(graph_data[0])

    A_position = np.random.permutation(n_var)
    A_cost = objective_function(np.append(A_position, A_position[0]), graph_data)
    print("Tour")
    

    objc_hist = [A_cost]
    best_tour = A_position
    best_fitness = A_cost

    print(f"{A_position},==> fitness_val: {A_cost} || best_tour: {best_tour}, ==> best_fitness_val: {best_fitness}")


    # SA algorithm
    T0 = 1
    T = T0
    alpha = 0.99
    max_iter = 50

    for iteration in range(1, max_iter + 1):
        B_position = create_neighbour(A_position)
        B_cost = objective_function(np.append(B_position, B_position[0]), graph_data)


        objc_hist.append(B_cost)

        delta = A_cost - B_cost

        if delta < 0:
            A_position = B_position
            A_cost = B_cost
        else:
            P = np.exp(-delta / T)
            r = np.random.rand()

            if r < P:
                A_position = B_position

        best_tour = A_position.copy()
        best_fitness = A_cost
        print(f"{B_position},==>fitness_val: {B_cost} || best_tour: {best_tour}, ==>best_fitness_val: {best_fitness}")
        
        T = alpha * T



simulated_annealing(graph_data)


Tour
[ 0 12  7  6 10  3  1 11  4  5  9  2  8],==> fitness_val: -17879 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  9  2  8], ==> best_fitness_val: -17879
[ 0 12  7  6 10 11  1  3  4  5  9  2  8],==>fitness_val: -17954 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  9  2  8], ==>best_fitness_val: -17879
[ 0 12  7  6 10  9  1 11  4  5  3  2  8],==>fitness_val: -17975 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  9  2  8], ==>best_fitness_val: -17879
[ 0 12  7  6 10  3  1  9  4  5 11  2  8],==>fitness_val: -20852 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  9  2  8], ==>best_fitness_val: -17879
[ 0 12  7  6 10  3  1 11  4  5  8  2  9],==>fitness_val: -17401 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  8  2  9], ==>best_fitness_val: -17401
[ 0 12  7  6 10  3  1  4 11  5  8  2  9],==>fitness_val: -18099 || best_tour: [ 0 12  7  6 10  3  1 11  4  5  8  2  9], ==>best_fitness_val: -17401
[ 0  7 12  6 10  3  1 11  4  5  8  2  9],==>fitness_val: -13850 || best_tour: [ 0  7 12  6 10  3  1 11  4